### ISSUE TITLE
Error: Cannot find module 'laravel-elixir/ingredients/commands/Utilities' 

### ISSUE THREAD

**Issue by joshea0** [joshea0/laravel-elixir-babel#1]
```
$ gulp
(node:24640) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
module.js:442
    throw err;
    ^

Error: Cannot find module 'laravel-elixir/ingredients/commands/Utilities'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/sponsorsmap/node_modules/laravel-elixir-babel/index.js:8:17)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

Found the same issue on a different project: https://github.com/peterreisz/laravel-elixir-ngtemplatecache/issues/1

Which was fixed by this commit: https://github.com/peterreisz/laravel-elixir-ngtemplatecache/commit/4a67a3d176de8e00dab86c32a411137d22d73219 (could probably figure out a fix based on that)

**Comment by joshea0** [comment]
For reference, here is my gulpfile.js:

```
var elixir = require('laravel-elixir');
require("laravel-elixir-babel");

elixir(function(mix) {
    //mix.sass('app.scss');
    mix.sass([
        'app.scss',
        'ovpr-banner.scss'
    ]);
    mix.babel("Sponsor.js");
});
```
